sudo: false

language: node_js
node_js:
  - "12"

notifications:
  email: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - chromium-browser

cache:
  directories:
    - ./node_modules

before_install:
  - cd web/onos-gui

install:
  - npm install

script:
  - npm run lint
  - npm run test -- --no-watch --no-progress --browsers=ChromiumHeadless
