apiVersion: v1
kind: Service
metadata:
  name: {{ template "onos-gui.fullname" . }}
  labels:
    app: {{ template "onos-gui.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "onos-gui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ template "onos-gui.fullname" . }}
    app: onos
    type: config
    resource: {{ template "onos-gui.fullname" . }}
    {{- include "onos-gui.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc-web-topo
      port: 8080
    - name: grpc-web-config
      port: 8081
    - name: web
      port: 80
